Gal 198/imd datastore
NHSDigital/Galleri-Invitations pull request #14
Opened 2023-07-24 16:19 UTC by msandhuNHS

## Description

## Context

## Type of changes

- [ ] Refactoring (non-breaking change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [ ] I have followed the code style of the project
- [ ] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [ ] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2023-07-24 16:57 UTC, LaithM96 requested changes
please read the comments and make the changes to fix the checks.

2023-07-24 16:57 UTC, LaithM96 commented on terraform/environment/dev/resources/dynamodb.tf
> +    range_key          = "ImdDecile"
"ImdDecile" is not matched to a defined attribute. That is, you're trying to use "ImdDecile" as a range_key in the aws_dynamodb_table "imd_table", but you didn't define it as an attribute.
You'll need to define "ImdDecile" as an attribute with a specific type (S, N, or B) in your resource block.

you may also need to Re-initialize your Terraform project with terraform init and refresh the state file with terraform refresh to update the status of your infrastructure.

2023-07-25 10:54 UTC, msandhuNHS commented on terraform/environment/dev/resources/dynamodb.tf
> +    range_key          = "ImdDecile"
All done.

2023-07-25 10:55 UTC, zainm97 requested changes

2023-07-25 11:09 UTC, msandhuNHS commented on terraform/environment/dev/resources/dynamodb.tf
> +    name               = "ImdRankImdDecileIndex"
Resolved.

2023-07-25 11:11 UTC, zainm97 commented on terraform/environment/dev/resources/dynamodb.tf
> +    name               = "ImdRankImdDecileIndex"
nice

2023-07-25 12:03 UTC, zainm97 approved these changes

2023-07-25 12:04 UTC, zainm97 approved these changes
Looks good

2023-07-25 16:06 UTC, LaithM96 approved these changes
Very good work, happy to approve.

2023-07-25 16:08 UTC, merged