Gal 254/load participating icb data
NHSDigital/Galleri-Invitations pull request #19
Opened 2023-07-31 09:33 UTC by zainm97

## Description

## Context

## Type of changes

- [ ] Refactoring (non-breaking change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [ ] I have followed the code style of the project
- [ ] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [ ] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2023-07-31 12:19 UTC, LaithM96 submitted a review, later dismissed
everything else looks good, well done :) It's important to thoroughly test your code in your specific environment to ensure it behaves as expected.

2023-08-01 10:04 UTC, msandhuNHS commented on .github/workflows/cicd-pipeline.yaml
> +      - develop
Need wildcard to account for every sprint etc. develop-[sprint number]

2023-08-01 10:09 UTC, msandhuNHS requested changes

2023-08-01 10:09 UTC, msandhuNHS commented on .github/workflows/cicd-pipeline.yaml
> +      - develop
Need wildcard to account for every sprint etc. develop-[sprint number]

2023-08-01 10:09 UTC, msandhuNHS commented on scripts/pipeline/seed-data.sh
> +  echo Succefully created data
Change to 'test data'

2023-08-01 10:25 UTC, LaithM96 approved these changes
all good, thanks :)

2023-08-01 10:27 UTC, msandhuNHS approved these changes

2023-08-01 10:27 UTC, merged