Gal 288/data cleanse gridall imd
NHSDigital/Galleri-Invitations pull request #24
Opened 2023-08-12 18:22 UTC by zainm97

## Description
Ticket: https://nhsd-jira.digital.nhs.uk/browse/GAL-288

This PR creates a lambda file which reads in 500Mb chunks of data from Gridall at a time, removes rows that don't qualify to the screening criteria and discards columns that are not needed. It does this for all the data of the Gridall file and again for the IMD file. It then deposits the filtered data back into an S3 bucket in CSV form. 

## Context

## Type of changes

- [ ] Refactoring (non-breaking change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [ ] I have followed the code style of the project
- [ ] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [ ] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2023-08-14 10:49 UTC, LaithM96 requested changes
Please have a look at the comments, once they have been reviewed and actioned, will be approving the PR, thank you :)

2023-08-14 10:49 UTC, LaithM96 commented on .editorconfig
>  indent_size = unset
this file looks good.

2023-08-14 10:49 UTC, LaithM96 commented on .github/workflows/cicd-pipeline.yaml
> +          echo "build_datetime=$datetime"
In the get-metadata job, the echo commands are used to set output variables. However, the syntax seems to be incorrect?. It should be echo "variable_name=value" >> $GITHUB_ENV instead of $GITHUB_OUTPUT.

2023-08-14 10:49 UTC, LaithM96 commented on .github/workflows/seeding.yaml
> +          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
Are the vars.AWS_ROLE_ARN and vars.AWS_REGION are correctly set ? and how do you check that ?

2023-08-14 10:49 UTC, LaithM96 commented on .github/workflows/terraform.yaml
> +        run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}"
is the run command for Terraform Init is misaligned ?

2023-08-14 10:49 UTC, LaithM96 commented on .github/workflows/terraform.yaml
> +        run: |
is the run command for Terraform Apply is misaligned ? if it's it will cause the yaml file to be invalid

2023-08-14 16:37 UTC, zainm97 commented on .github/workflows/terraform.yaml
> +        run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}"
nope

2023-08-14 16:38 UTC, zainm97 commented on .github/workflows/seeding.yaml
> +          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
you can check it using our repo variables on github. navigate to github invitations repo -> setting -> env variables and you'll see the variables that we grab

2023-08-14 16:39 UTC, zainm97 commented on .github/workflows/cicd-pipeline.yaml
> +          echo "build_datetime=$datetime"
change from nhs england template team. i just split it into two lines because our linter complains

2023-08-14 16:39 UTC, zainm97 commented on .editorconfig
>  indent_size = unset
yallah habibi

2023-08-14 16:43 UTC, LaithM96 approved these changes
happy with the comments after I have request changes, so I am happy to approve it. good work

2023-08-15 09:17 UTC, msandhuNHS approved these changes
Approved.

2023-08-15 10:33 UTC, LaithM96 approved these changes
all good, checks passed

2023-08-15 10:48 UTC, msandhuNHS approved these changes

2023-08-15 11:07 UTC, merged