Gal 316/target percentage
NHSDigital/Galleri-Invitations pull request #81
Opened 2023-10-23 15:47 UTC by Abdul-NHS

## Description
https://nhsd-jira.digital.nhs.uk/browse/GAL-316

Created GET and PUT API endpoints for clinic invitation criteria component

## Context

## Type of changes

- [ ] Refactoring (non-breaking change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [ ] I have followed the code style of the project
- [ ] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [ ] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2023-10-24 11:04 UTC, zainm97 commented on terraform/environment/dev/resources/lambda.tf
> +  s3_key    = aws_s3_object.target_fill_to_percentage_put_lambda.key // may need to change
remove comment

2023-10-24 11:10 UTC, zainm97 commented on terraform/environment/dev/resources/lambda/targetFillToPercentage/lambdaHandler/targetFillToPercentageLambda.js
> +  Lambda to load invitation parameters and pass on to GPS client.
adjust comment to reflect target fill to instead

2023-10-24 11:12 UTC, zainm97 commented on terraform/environment/dev/resources/lambda/targetFillToPercentage/lambdaHandler/targetFillToPercentageLambda.js
> +  const attribute = {targetPercentage: response.Item.TARGET_PERCENTAGE};
use response?.Item.TARGET_PERCENTAGE to catch the case where the response does not return an item. Think we want to handle that error gracefully too

2023-10-24 11:17 UTC, zainm97 commented on terraform/environment/dev/resources/lambda/targetFillToPercentagePut/lambdaHandler/targetFillToPercentagePutLambda.js
> +  const CONFIG_ID = 1;
move to line 2

2023-10-24 11:17 UTC, zainm97 commented on terraform/environment/dev/resources/lambda/targetFillToPercentagePut/lambdaHandler/targetFillToPercentagePutLambda.js
> +  const targetPercentage =  event.body !== null ? JSON.parse(event.body).targetPercentage:"";
nit picky but space before the colon and after

2023-10-24 11:20 UTC, zainm97 requested changes
Code in the backend looks good. Would want to make a small request just so that going forward its easier to see at a glance what lambdas are doing for the api gateway. Could we add a "get" somewhere for the target fill to percentage. 

Also, need to add a npm i prefix to the terraform apply stage on the pipeline so that we submit out node modules folder as part of the lambda zip file

All changes i've requested are minor ones and dont impact functionality but good work fellas

2023-10-24 13:45 UTC, Abdul-NHS commented on terraform/environment/dev/resources/lambda/targetFillToPercentage/lambdaHandler/targetFillToPercentageLambda.js
> +  const attribute = {targetPercentage: response.Item.TARGET_PERCENTAGE};
if (response.Item.hasOwnProperty("TARGET_PERCENTAGE")) catches whether or not the response has the item object with the target percentage inside. Therefore anything not matching this will result in a 404 error, i.e. item is not null

2023-10-24 13:55 UTC, zainm97 commented on terraform/environment/dev/resources/lambda/targetFillToPercentage/lambdaHandler/targetFillToPercentageLambda.js
> +  const attribute = {targetPercentage: response.Item.TARGET_PERCENTAGE};
currently dont have `if (response.Item.hasOwnProperty("TARGET_PERCENTAGE"))` implemented. Only line 24 you're making the assumption that Item is being returned from the response and that it has TARGET_PERCENTAGE. In line 26 youre just check if the response has returned item. So there is no check to see if TARGER_PERCENTAGE is valid

2023-10-25 14:33 UTC, msandhuNHS approved these changes

2023-10-25 14:33 UTC, merged