Gal 473/lsoa midpoint calc
NHSDigital/Galleri-Invitations pull request #88
Opened 2023-10-26 16:41 UTC by Abdul-NHS

## Description
Create new csv with average easting and average northing attached to the lsoa csv file, and remove postcodes

## Context

## Type of changes

- [ ] Refactoring (non-breaking change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [x] I have followed the code style of the project
- [ ] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [ ] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2023-10-26 21:10 UTC, zainm97 commented on scripts/pipeline/nonprod_postcode_load/nonprod_postcode_load.py
> +    for i in range(1, 10, 1):
think this was a rebase issue so my fault. Can you revert this back to the previous change

2023-10-26 21:11 UTC, zainm97 commented on scripts/pipeline/seed-data.sh
> +  # echo Initiating upload of Participating ICBs test data to database
think this was a rebase issue so my fault. Can you revert this back to the previous change

2023-10-26 21:11 UTC, zainm97 commented on scripts/pipeline/seed-data.sh
> +  aws s3 cp s3://galleri-ons-data/lsoa_data_/unique_lsoa_data.csv ./nonprod-lsoa-data
think this was a rebase issue so my fault. Can you revert this back to the previous change

2023-10-26 21:15 UTC, zainm97 commented on terraform/environment/dev/resources/lambda/getLsoaInRange/lambdaHandler/getLsoaInRangeLambda.js
> +    "*************\n Event = " + JSON.stringify(event, null, 2) + "\n**********"
think this was a rebase issue so my fault. Can you revert this back to the previous change

2023-10-26 21:17 UTC, zainm97 commented on terraform/environment/dev/resources/lambda/getLsoaParticipants/lambdaHandler/getLsoaParticipantsLambda.js
> +  const lsoaList = [
think this was a rebase issue so my fault. Can you revert this file back to the previous change

2023-10-27 10:22 UTC, Abdul-NHS commented on scripts/pipeline/nonprod_postcode_load/nonprod_postcode_load.py
> +    for i in range(1, 10, 1):
Reverted change

2023-10-27 10:22 UTC, Abdul-NHS commented on scripts/pipeline/seed-data.sh
> +  # echo Initiating upload of Participating ICBs test data to database
Reverted change

2023-10-27 10:23 UTC, Abdul-NHS commented on terraform/environment/dev/resources/lambda/getLsoaInRange/lambdaHandler/getLsoaInRangeLambda.js
> +    "*************\n Event = " + JSON.stringify(event, null, 2) + "\n**********"
reverted change

2023-10-27 10:56 UTC, Abdul-NHS commented on terraform/environment/dev/resources/lambda/getLsoaParticipants/lambdaHandler/getLsoaParticipantsLambda.js
> +  const lsoaList = [
Have actioned by removing prettier formating

2023-10-30 13:19 UTC, zainm97 requested changes
All looks good, could you just move the uploadUniqueLsoa.js into the test_data folder and happy to approve

2023-10-30 14:10 UTC, zainm97 approved these changes
Good stuff. I'll adjust the z_rename folder in Gal-403

2023-11-01 17:09 UTC, closed without merging